Update & Fix Japanese.
EhViewer-NekoInverter/EhViewer pull request #72
Opened 2024-11-01 16:28 UTC by reindex-ot

2024-11-01 16:40 UTC, xb2016 commented
Thank you for providing the translation. However, the Japanese translation file is located at `app/src/main/res/values-ja/strings.xml`. Please correct it and resubmit.

2024-11-01 23:41 UTC, reindex-ot commented
Maybe I was tired, but I chose the wrong directory.
Sorry.

2024-11-02 04:11 UTC, xb2016 requested changes
Since I don’t understand Japanese, I used ChatGPT to review the translation.
Please confirm if the reviewed content needs any changes.

Also, I noticed that a half-width colon is used consistently in the translation, is this common in Japanese?

Thank you once again for your contribution to the project.

2024-11-04 01:27 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="sign_in_via_webview">WebView でログイン</string>
❌️

2024-11-04 01:28 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="from_clipboard">クリップボードから</string>
❌️

2024-11-04 01:28 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="app_waring">このアプリの内容はインターネットから取得したものです。その内容の一部は心身に悪影響を与える可能性があります。\n使用を続行することで規約に同意したとみなされます。</string>
❌️

2024-11-04 01:29 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="cookie_explain">Cookie とは、ウェブブラウザに保存される小さなデータのことです。Cookie が何なのか、または取得方法がわからない場合は Google で検索をしてください。\n\nログインをするには特別な Cookie を入力してください。</string>
❌️

2024-11-04 01:29 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="sign_in_failed_tip">この問題が解決しない場合は「WebView でログイン」か「Cookie でログイン」をお試しください。</string>
❌️

2024-11-04 01:29 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="settings_eh_thumb_show_title">タイトル表示のサムネイルモード</string>
❌️

2024-11-04 01:30 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="settings_eh_image_limits_summary_acc">現在: %1$d / %2$d</string>
❌️

2024-11-04 02:10 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="settings_eh_thumb_show_title">タイトル表示のサムネイルモード</string>
❌️

2024-11-04 02:14 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="current_funds">Fund: %1$s - GP: %2$d クレジット</string>
update text.
` <string name="current_funds">Fund: %1$s | GP: %2$d Credit</string>`

2024-11-04 02:16 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="stat_download_done_text_mix">%1$d 件のダウンロードが成功、%2$d 件が失敗</string>
update text.
````
    <string name="stat_download_done_text_succeeded">%d 件が成功しました</string>
    <string name="stat_download_done_text_failed">%d 件が失敗しました</string>
    <string name="stat_download_done_text_mix">%1$d 件のダウンロードが成功、%2$d 件が失敗しました</string>
````

2024-11-04 02:17 UTC, xb2016 commented on app/src/main/res/values-ja/strings.xml
> +    <string name="current_funds">Fund: %1$s - GP: %2$d クレジット</string>
Fund: %1$s GP | %2$d Credit

2024-11-04 08:34 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="current_funds">Fund: %1$s - GP: %2$d クレジット</string>
Changed
````
    <string name="current_funds">資金: %1$s | GP: %2$d Credits</string>
    <string name="insufficient_funds">資金 (GP) が不足しています</string>
````

2024-11-04 08:53 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="current_funds">Fund: %1$s - GP: %2$d クレジット</string>
Pipe removed.

2024-11-04 11:07 UTC, reindex-ot commented on app/src/main/res/values-ja/strings.xml
> +    <string name="current_funds">Fund: %1$s - GP: %2$d クレジット</string>
Restore text.
```
    <string name="current_funds">Funds: %1$s GP, %2$d Credits</string>
    <string name="insufficient_funds">Funds (GP) が不足しています</string>
````

2024-11-04 11:09 UTC, merged